"""Self-contained HTML/CSS/JavaScript for the rescue game."""

GAME_HTML = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>四船协同搜救小游戏</title>
<style>
:root{--ink:#17333d;--muted:#667d86;--line:#cadce2;--water:#dff4f8;--panel:#f7fafb;--blue:#1677ff;--green:#00a870;--orange:#f59e0b;--purple:#8b5cf6;--red:#df3f48}
*{box-sizing:border-box}body{margin:0;background:#edf3f5;color:var(--ink);font-family:"Microsoft YaHei UI","PingFang SC",sans-serif}
header{height:62px;padding:0 20px;background:#fff;border-bottom:1px solid #d7e3e7;display:flex;align-items:center;justify-content:space-between}
h1{font-size:20px;margin:0}.header-state{font-size:13px;color:var(--muted)}
main{display:grid;grid-template-columns:minmax(560px,1fr) 330px;gap:12px;padding:12px;max-width:1500px;margin:auto}
.stage,.controls{background:#fff;border:1px solid #d5e2e6;border-radius:10px;box-shadow:0 2px 8px #20343d18}.stage{padding:12px;min-width:0}
.canvas-wrap{width:100%;aspect-ratio:1/1;max-height:calc(100vh - 112px);margin:auto;position:relative}canvas{display:block;width:100%;height:100%;cursor:crosshair;touch-action:none}
.controls{padding:15px;max-height:calc(100vh - 86px);overflow:auto}.controls h2{font-size:15px;margin:2px 0 9px}.section{padding-bottom:14px;margin-bottom:14px;border-bottom:1px solid #e1eaed}
label{display:block;font-size:13px;color:var(--muted);margin-bottom:6px}.row{display:flex;gap:7px;align-items:center;margin-bottom:8px}.row>*{min-width:0}
input[type=number],select{width:100%;height:38px;border:1px solid #b9ccd3;border-radius:6px;padding:0 9px;font:inherit;color:var(--ink);background:#fff}
input[type=range]{width:100%}button{min-height:38px;border:0;border-radius:6px;padding:8px 10px;background:#e5eef1;color:var(--ink);font:600 13px "Microsoft YaHei UI",sans-serif;cursor:pointer}button:hover{filter:brightness(.97)}button.primary{background:#176f87;color:#fff}button.danger{background:#c53b35;color:#fff}button:disabled{opacity:.45;cursor:not-allowed}
.mode button{flex:1}.mode button.active{background:#176f87;color:#fff}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:10px}.stat{background:var(--panel);padding:8px;border-radius:6px;text-align:center}.stat b{display:block;font-size:18px}.stat span{font-size:11px;color:var(--muted)}
.progress{height:8px;background:#e2ebee;border-radius:8px;overflow:hidden}.progress i{display:block;height:100%;width:0;background:#16a36a;transition:width .2s}
.fleet{font:12px/1.65 Consolas,"Microsoft YaHei UI",monospace;background:var(--panel);border-radius:7px;padding:9px;white-space:pre-wrap}.hint{font-size:12px;color:var(--muted);line-height:1.6}.error{min-height:20px;color:#b4232d;font-size:12px}.speed-value{font-weight:600;color:var(--ink)}
@media(max-width:900px){header{height:auto;padding:11px 14px;display:block}.header-state{margin-top:4px}main{grid-template-columns:1fr}.canvas-wrap{max-height:none}.controls{max-height:none;overflow:visible}}
</style></head>
<body><header><h1>四船协同搜救小游戏</h1><div id="headerState" class="header-state" aria-live="polite">60 × 60 cm 模拟场地 · 等待布置目标</div></header>
<main><section class="stage"><div class="canvas-wrap"><canvas id="field" aria-label="60厘米乘60厘米搜救场地，可点击添加小人"></canvas></div></section>
<aside class="controls">
 <div class="section"><h2>布置小人</h2><label for="personCount">随机生成数量（1–1000）</label><div class="row"><input id="personCount" type="number" min="1" max="1000" value="20"><button id="generateBtn" class="primary">随机布置</button></div>
 <div class="row mode"><button id="addMode" class="active">点击添加</button><button id="eraseMode">点击删除</button></div><div class="hint">点击场地可自行放置；基站和船体安全区内不能放置。拖动也可连续添加或删除。</div></div>
 <div class="section"><h2>选择算法</h2><label for="algorithm">任务分配与访问顺序</label><select id="algorithm"><option value="balanced">均衡最近邻（1–1000，推荐）</option><option value="partition">分区最近邻（1–1000，快速）</option><option value="exact">精确四船动态规划（1–12）</option></select><div id="algorithmInfo" class="hint" style="margin-top:7px"></div></div>
 <div class="section"><h2>开始搜救</h2><div class="row"><button id="startBtn" class="primary" style="flex:1">开始搜救</button><button id="pauseBtn" style="flex:1" disabled>暂停</button></div><div class="row"><button id="resetBtn" style="flex:1">船只归位</button><button id="clearBtn" class="danger" style="flex:1">清空小人</button></div>
 <label for="speed">动画速度：<span id="speedValue" class="speed-value">6×</span></label><input id="speed" type="range" min="1" max="30" value="6"></div>
 <div class="section"><h2>救援进度</h2><div class="stats" aria-live="polite"><div class="stat"><b id="total">0</b><span>目标</span></div><div class="stat"><b id="rescued">0</b><span>已救</span></div><div class="stat"><b id="elapsed">0.0</b><span>模拟秒</span></div></div><div id="progress" class="progress" role="progressbar" aria-label="救援进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="progressBar"></i></div></div>
 <div class="section"><h2>四船任务</h2><div id="fleet" class="fleet">尚未规划</div></div>
 <div id="error" class="error" role="alert"></div><div class="hint">算法：均衡最近邻分配 + 矩形基站可见图避障。该启发式支持 1–1000 个目标，优先兼顾总航程和四船工作量均衡。</div>
</aside></main>
<script>
const canvas=document.getElementById('field'),ctx=canvas.getContext('2d');
const FIELD=60,BASE={x:19,y:22.5,w:22,h:15},SAFE={x:16,y:19.5,w:28,h:21};
const COLORS=['#1677ff','#00a870','#f59e0b','#8b5cf6'];
const DOCKS=[{x:22.5,y:27,a:Math.PI,exit:{x:15.4,y:27}},{x:22.5,y:33,a:Math.PI,exit:{x:15.4,y:33}},{x:37.5,y:27,a:0,exit:{x:44.6,y:27}},{x:37.5,y:33,a:0,exit:{x:44.6,y:33}}];
let people=[],boats=[],mode='add',phase='idle',lastTime=0,elapsed=0,dragging=false,nextId=1;
const $=id=>document.getElementById(id);
function newBoats(){boats=DOCKS.map((d,i)=>({id:i+1,x:d.x,y:d.y,a:d.a,color:COLORS[i],steps:[],index:0,assigned:0,rescued:0,distance:0}))}
newBoats();
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
addEventListener('resize',resize);resize();
function P(x,y){const w=canvas.clientWidth,h=canvas.clientHeight,pad=34,s=Math.min((w-2*pad)/FIELD,(h-2*pad)/FIELD),ox=(w-FIELD*s)/2,oy=(h-FIELD*s)/2;return[ox+x*s,oy+(FIELD-y)*s,s,ox,oy]}
function worldFromEvent(e){const r=canvas.getBoundingClientRect(),[,,s,ox,oy]=P(0,0);return{x:(e.clientX-r.left-ox)/s,y:FIELD-(e.clientY-r.top-oy)/s}}
function inside(p,r,margin=0){return p.x>r.x-margin&&p.x<r.x+r.w+margin&&p.y>r.y-margin&&p.y<r.y+r.h+margin}
function validPerson(p){return p.x>=.7&&p.x<=59.3&&p.y>=.7&&p.y<=59.3&&!inside(p,SAFE)}
function addPerson(p){if(people.length>=1000){showError('最多放置 1000 个小人');return}if(!validPerson(p)){showError('这里属于基站或船体安全区，不能放置小人');return}if(people.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<.35))return;people.push({id:nextId++,x:p.x,y:p.y,rescued:false,boat:0});showError('');updateUI();draw()}
function erasePerson(p){let best=-1,dist=1.3;people.forEach((q,i)=>{const d=Math.hypot(q.x-p.x,q.y-p.y);if(d<dist){dist=d;best=i}});if(best>=0){people.splice(best,1);updateUI();draw()}}
function editAt(e){if(phase==='running'||phase==='paused'||phase==='planning'){showError('请先让船只归位，再修改目标');return}const p=worldFromEvent(e);mode==='add'?addPerson(p):erasePerson(p)}
canvas.addEventListener('pointerdown',e=>{dragging=true;canvas.setPointerCapture(e.pointerId);editAt(e)});canvas.addEventListener('pointermove',e=>{if(dragging)editAt(e)});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
function randomPeople(n){people=[];nextId=1;let attempts=0;while(people.length<n&&attempts<n*80){attempts++;const p={x:.8+Math.random()*58.4,y:.8+Math.random()*58.4};if(validPerson(p)&&!people.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<(n>300?.18:.42)))people.push({id:nextId++,x:p.x,y:p.y,rescued:false,boat:0})}if(people.length<n)showError(`场地密度较高，只成功放置 ${people.length} 个目标`);else showError('');resetBoats(false);updateUI();draw()}
function segmentHitsRect(a,b,r){let lo=0,hi=1;for(const [p,d,min,max] of [[a.x,b.x-a.x,r.x,r.x+r.w],[a.y,b.y-a.y,r.y,r.y+r.h]]){if(Math.abs(d)<1e-9){if(p<=min||p>=max)return false;continue}let t1=(min-p)/d,t2=(max-p)/d;if(t1>t2)[t1,t2]=[t2,t1];lo=Math.max(lo,t1);hi=Math.min(hi,t2);if(lo>=hi-1e-9)return false}return hi>0&&lo<1}
function shortestPath(a,b){if(!segmentHitsRect(a,b,SAFE))return{points:[b],distance:Math.hypot(b.x-a.x,b.y-a.y)};const c=[{x:SAFE.x,y:SAFE.y},{x:SAFE.x+SAFE.w,y:SAFE.y},{x:SAFE.x+SAFE.w,y:SAFE.y+SAFE.h},{x:SAFE.x,y:SAFE.y+SAFE.h}],nodes=[a,b,...c],N=6,dist=Array(N).fill(Infinity),prev=Array(N).fill(-1),used=Array(N).fill(false);dist[0]=0;for(let z=0;z<N;z++){let u=-1;for(let i=0;i<N;i++)if(!used[i]&&(u<0||dist[i]<dist[u]))u=i;if(u<0||!isFinite(dist[u]))break;used[u]=true;for(let v=0;v<N;v++){if(u===v||segmentHitsRect(nodes[u],nodes[v],SAFE))continue;const nd=dist[u]+Math.hypot(nodes[v].x-nodes[u].x,nodes[v].y-nodes[u].y);if(nd<dist[v]){dist[v]=nd;prev[v]=u}}}let ids=[],u=1;while(u>0){ids.push(u);u=prev[u];if(u<0)break}ids.reverse();return{points:ids.map(i=>nodes[i]),distance:dist[1]}}
function preparePlan(){people.forEach(p=>{p.rescued=false;p.boat=0});newBoats();boats.forEach((b,i)=>b.steps=[{x:DOCKS[i].exit.x,y:DOCKS[i].exit.y,person:null}])}
function appendOrder(bi,order){let cursor={x:DOCKS[bi].exit.x,y:DOCKS[bi].exit.y};for(const pi of order){const p=people[pi],path=shortestPath(cursor,p);path.points.forEach((q,k)=>boats[bi].steps.push({x:q.x,y:q.y,person:k===path.points.length-1?p.id:null}));p.boat=bi+1;boats[bi].assigned++;boats[bi].distance+=path.distance;cursor={x:p.x,y:p.y}}}
function planBalanced(){preparePlan();const remaining=new Set(people.map((_,i)=>i)),cursor=DOCKS.map(d=>({x:d.exit.x,y:d.exit.y})),loads=[0,0,0,0],orders=[[],[],[],[]];while(remaining.size){let best=null;for(let bi=0;bi<4;bi++)for(const pi of remaining){const p=people[pi],d=shortestPath(cursor[bi],p).distance,score=loads[bi]+d;if(!best||score<best.score)best={bi,pi,d,score}}const{bi,pi,d}=best,p=people[pi];orders[bi].push(pi);loads[bi]+=d;cursor[bi]={x:p.x,y:p.y};remaining.delete(pi)}orders.forEach((order,bi)=>appendOrder(bi,order))}
function planPartition(){preparePlan();const groups=[[],[],[],[]];people.forEach((p,pi)=>{let best=0,cost=Infinity;for(let bi=0;bi<4;bi++){const d=shortestPath(DOCKS[bi].exit,p).distance;if(d<cost){cost=d;best=bi}}groups[best].push(pi)});groups.forEach((group,bi)=>{const order=[],remaining=new Set(group);let cursor={x:DOCKS[bi].exit.x,y:DOCKS[bi].exit.y};while(remaining.size){let pick=-1,cost=Infinity;for(const pi of remaining){const d=shortestPath(cursor,people[pi]).distance;if(d<cost){cost=d;pick=pi}}order.push(pick);cursor={x:people[pick].x,y:people[pick].y};remaining.delete(pick)}appendOrder(bi,order)})}
function exactBoatTable(bi,pair){const n=people.length,size=1<<n,dp=new Float64Array(size*n),parent=new Int16Array(size*n),bestCost=new Float64Array(size),bestEnd=new Int16Array(size);dp.fill(Infinity);parent.fill(-1);bestCost.fill(Infinity);bestEnd.fill(-1);bestCost[0]=0;for(let e=0;e<n;e++)dp[(1<<e)*n+e]=shortestPath(DOCKS[bi].exit,people[e]).distance;for(let mask=1;mask<size;mask++)for(let end=0;end<n;end++){const idx=mask*n+end,cost=dp[idx];if(!(mask&(1<<end))||!isFinite(cost))continue;if(cost<bestCost[mask]){bestCost[mask]=cost;bestEnd[mask]=end}for(let next=0;next<n;next++){if(mask&(1<<next))continue;const nm=mask|(1<<next),ni=nm*n+next,nc=cost+pair[end][next];if(nc<dp[ni]){dp[ni]=nc;parent[ni]=end}}}return{n,dp,parent,bestCost,bestEnd}}
function exactOrder(table,mask){const out=[];let end=table.bestEnd[mask];while(mask&&end>=0){out.push(end);const previous=table.parent[mask*table.n+end];mask^=1<<end;end=previous}return out.reverse()}
function planExact(){preparePlan();const n=people.length,pair=Array.from({length:n},()=>new Float64Array(n));for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)pair[i][j]=pair[j][i]=shortestPath(people[i],people[j]).distance;const tables=[0,1,2,3].map(bi=>exactBoatTable(bi,pair)),memo=new Map();function solve(bi,remaining){if(bi===4)return remaining===0?{max:0,total:0,masks:[]}:null;const key=bi+','+remaining;if(memo.has(key))return memo.get(key);let best=null,sub=remaining;do{const next=solve(bi+1,remaining^sub);if(next){const cost=tables[bi].bestCost[sub],candidate={max:Math.max(cost,next.max),total:cost+next.total,masks:[sub,...next.masks]};if(!best||candidate.max<best.max-1e-9||(Math.abs(candidate.max-best.max)<1e-9&&candidate.total<best.total))best=candidate}if(sub===0)break;sub=(sub-1)&remaining}while(true);memo.set(key,best);return best}const result=solve(0,(1<<n)-1);result.masks.forEach((mask,bi)=>appendOrder(bi,exactOrder(tables[bi],mask)))}
function plan(){const algorithm=$('algorithm').value;if(algorithm==='exact')planExact();else if(algorithm==='partition')planPartition();else planBalanced()}
function start(){if(!people.length){showError('请先点击场地添加小人，或随机生成 1–1000 个目标');return}if($('algorithm').value==='exact'&&people.length>12){showError('精确四船动态规划最多支持 12 个目标；请减少人数或选择均衡/分区最近邻');return}phase='planning';elapsed=0;$('startBtn').disabled=true;$('pauseBtn').disabled=true;showError(`正在使用“${$('algorithm').selectedOptions[0].text}”规划 ${people.length} 个目标……`);updateUI();draw();setTimeout(()=>{plan();phase='running';showError('');lastTime=performance.now();$('pauseBtn').disabled=false;$('pauseBtn').textContent='暂停';requestAnimationFrame(tick);updateUI();draw()},30)}
function tick(now){if(phase!=='running')return;const realDt=Math.min((now-lastTime)/1000,.08);lastTime=now;const mult=+$('speed').value,simDt=realDt*mult;elapsed+=simDt;let active=0;for(const b of boats){let move=4.2*simDt;while(move>0&&b.index<b.steps.length){active++;const t=b.steps[b.index],dx=t.x-b.x,dy=t.y-b.y,d=Math.hypot(dx,dy);if(d<.025){b.x=t.x;b.y=t.y;b.index++;if(t.person){const p=people.find(q=>q.id===t.person);if(p&&!p.rescued){p.rescued=true;b.rescued++}}continue}b.a=Math.atan2(dy,dx);if(move>=d){b.x=t.x;b.y=t.y;move-=d}else{b.x+=dx/d*move;b.y+=dy/d*move;move=0}}}updateUI();draw();if(people.every(p=>p.rescued)){phase='done';$('pauseBtn').disabled=true;$('startBtn').disabled=false;$('startBtn').textContent='再次搜救';$('headerState').textContent=`搜救完成 · ${people.length} 人 · 模拟用时 ${elapsed.toFixed(1)} 秒`;return}requestAnimationFrame(tick)}
function pause(){if(phase==='running'){phase='paused';$('pauseBtn').textContent='继续'}else if(phase==='paused'){phase='running';$('pauseBtn').textContent='暂停';lastTime=performance.now();requestAnimationFrame(tick)}updateUI()}
function resetBoats(redraw=true){phase='idle';elapsed=0;people.forEach(p=>{p.rescued=false;p.boat=0});newBoats();$('startBtn').disabled=false;$('startBtn').textContent='开始搜救';$('pauseBtn').disabled=true;$('pauseBtn').textContent='暂停';if(redraw){updateUI();draw()}}
function clearAll(){people=[];nextId=1;resetBoats(false);showError('');updateUI();draw()}
function updateUI(){const done=people.filter(p=>p.rescued).length,pct=people.length?done/people.length*100:0;$('total').textContent=people.length;$('rescued').textContent=done;$('elapsed').textContent=elapsed.toFixed(1);$('progressBar').style.width=pct+'%';$('progress').setAttribute('aria-valuenow',Math.round(pct));$('headerState').textContent=phase==='planning'?`正在规划 ${people.length} 个目标……`:phase==='running'?`搜救进行中 · ${done}/${people.length}`:phase==='paused'?`已暂停 · ${done}/${people.length}`:phase==='done'?`搜救完成 · ${done}/${people.length}`:`60 × 60 cm · 已布置 ${people.length} 人`;$('fleet').textContent=boats.map(b=>`船 ${b.id}  分配 ${b.assigned.toString().padStart(3)}  已救 ${b.rescued.toString().padStart(3)}  路程 ${b.distance.toFixed(1).padStart(6)} cm`).join('\n')}
function showError(s){$('error').textContent=s}
function draw(){const W=canvas.clientWidth,H=canvas.clientHeight,[x0,yBottom,s,ox,oy]=P(0,0),[,yTop]=P(0,FIELD);ctx.clearRect(0,0,W,H);ctx.fillStyle='#dff4f8';ctx.fillRect(ox,oy,FIELD*s,FIELD*s);ctx.strokeStyle='#325d6b';ctx.lineWidth=2;ctx.strokeRect(ox,oy,FIELD*s,FIELD*s);ctx.strokeStyle='#c5e0e6';ctx.lineWidth=1;for(let n=5;n<FIELD;n+=5){let[x]=P(n,0),[,y]=P(0,n);line(x,oy,x,oy+FIELD*s);line(ox,y,ox+FIELD*s,y)}ctx.fillStyle='#526b74';ctx.font='11px Arial';ctx.textAlign='center';for(let n=0;n<=60;n+=10){let[x,y]=P(n,0);ctx.fillText(n+'cm',x,y+18)}ctx.textAlign='right';for(let n=0;n<=60;n+=10){let[x,y]=P(0,n);ctx.fillText(n+'cm',x-7,y+4)}
 const [bx,by]=P(BASE.x,BASE.y+BASE.h);ctx.fillStyle='#58636a';ctx.fillRect(bx,by,BASE.w*s,BASE.h*s);ctx.strokeStyle='#2f3940';ctx.lineWidth=2;ctx.strokeRect(bx,by,BASE.w*s,BASE.h*s);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 13px "Microsoft YaHei UI"';ctx.fillText('中央基站 22 × 15 cm',bx+BASE.w*s/2,by+BASE.h*s/2+4);
 if(phase==='running'||phase==='paused'||phase==='done')for(const b of boats){if(b.index>=b.steps.length)continue;ctx.beginPath();ctx.moveTo(...P(b.x,b.y));for(let i=b.index;i<b.steps.length;i++)ctx.lineTo(...P(b.steps[i].x,b.steps[i].y));ctx.strokeStyle=b.color+'99';ctx.lineWidth=2;ctx.stroke()}
 const pr=people.length>500?1.7:people.length>150?2.4:3.2;for(const p of people){const[x,y]=P(p.x,p.y);ctx.beginPath();ctx.arc(x,y,pr,0,Math.PI*2);ctx.fillStyle=p.rescued?'#16a36a':'#df3f48';ctx.fill();if(people.length<=60){ctx.fillStyle='#29434d';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(p.id,x,y-7)}}
 for(const b of boats)drawBoat(b,s);ctx.fillStyle='#315a68';ctx.font='12px "Microsoft YaHei UI"';ctx.textAlign='left';ctx.fillText('点击水域添加小人',ox+8,oy+17)}
function drawBoat(b,s){const[x,y]=P(b.x,b.y),L=7*s,W=5*s;ctx.save();ctx.translate(x,y);ctx.rotate(-b.a);ctx.fillStyle=b.color;ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(L/2,0);ctx.lineTo(L/2-1.5*s,-W/2);ctx.lineTo(-L/2,-W/2);ctx.lineTo(-L/2,W/2);ctx.lineTo(L/2-1.5*s,W/2);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.id,0,0);ctx.restore()}
function line(a,b,c,d){ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()}
const ALGORITHM_INFO={balanced:'每轮综合“当前累计航程 + 到目标距离”，四船负载更均衡，适合 1–1000 人。',partition:'先把目标分给最近的出坞口，再分别执行最近邻访问；计算最快，但目标分布不均时船间负载可能失衡。',exact:'枚举四船目标子集并用 Held–Karp 动态规划优化访问顺序；适合 1–12 人，目标是最小化最忙船的航程。'};function updateAlgorithmInfo(){$('algorithmInfo').textContent=ALGORITHM_INFO[$('algorithm').value]}
$('generateBtn').onclick=()=>{let n=Math.max(1,Math.min(1000,parseInt($('personCount').value)||1));$('personCount').value=n;randomPeople(n)};$('addMode').onclick=()=>{mode='add';$('addMode').classList.add('active');$('eraseMode').classList.remove('active')};$('eraseMode').onclick=()=>{mode='erase';$('eraseMode').classList.add('active');$('addMode').classList.remove('active')};$('algorithm').onchange=()=>{updateAlgorithmInfo();resetBoats()};$('startBtn').onclick=start;$('pauseBtn').onclick=pause;$('resetBtn').onclick=()=>resetBoats();$('clearBtn').onclick=clearAll;$('speed').oninput=()=>$('speedValue').textContent=$('speed').value+'×';updateAlgorithmInfo();updateUI();draw();
</script></body></html>'''
