using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Waypoint autopilot. Converts a planned route into throttle/rudder commands
/// for the physics hull (BoatPhysics) instead of moving the transform directly.
/// Keeps the starboard-passing rule for head-on approaches.
/// </summary>
public class BoatController : MonoBehaviour
{
    private static readonly List<BoatController> ActiveBoats = new List<BoatController>();

    [Header("Identity")]
    public string boatId;
    public Color routeColor = Color.white;

    [Header("Autopilot")]
    [Tooltip("Recommended deterministic simulation mode. Disable only when tuning the experimental force-based hull controller.")]
    public bool useKinematicAutopilot = true;
    public float turnSpeedDegrees = 140f;
    [Tooltip("A waypoint is consumed once the hull comes this close (m).")]
    public float waypointTolerance = 0.015f;
    public float cruiseSpeed = 0.15f;
    public float rudderGain = 2.1f;
    [Tooltip("Yaw-rate damping: rudder degrees per deg/s of yaw rate (PD controller D term).")]
    public float rudderDampGain = 1.2f;
    [Tooltip("Lookahead distance along the route (m). Waypoint-spacing independent.")]
    public float lookaheadDistance = 0.09f;
    [Tooltip("Desired speed shrinks with heading error; 1/40 => full slowdown at 40 deg error.")]
    public float headingErrSpeedGain = 1f / 40f;
    [Tooltip("Minimum fraction of cruise speed kept at large heading error (breaks the corner orbit).")]
    public float headingErrSpeedFloor = 0.03f;
    [Tooltip("Minimum desired speed (m/s) so the hull does not stall short of the waypoint.")]
    public float distanceSpeedFloor = 0.002f;

    [Header("Rescue and avoidance")]
    public float rescueRadius = 0.025f;
    public float avoidanceRadius = 0.105f;
    public float minimumSeparation = 0.052f;

    private BoatPhysics physics;
    private readonly List<Vector3> route = new List<Vector3>();
    private int waypointIndex;
    private int acceptedVersion = -1;
    private bool emergencyStopped;
    private LineRenderer routeRenderer;
    private string missionStatus = "泊位待命";
    private int fixedTickCount;
    private Vector3 reservedPosition;
    private Quaternion reservedRotation;
    private float reservedTick = -1f;
    public bool WaitingForTraffic { get; private set; }

    public bool IsMoving => !emergencyStopped && waypointIndex < route.Count;
    public bool HasRoute => route.Count > 0;
    public bool RouteComplete => route.Count > 0 && waypointIndex >= route.Count;
    public string MissionStatus => missionStatus;
    public int FixedTickCount => fixedTickCount;
    public BoatPhysics Physics => physics;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    private static void ResetActiveFleet()
    {
        // Required when Enter Play Mode Options has domain reload disabled.
        ActiveBoats.Clear();
    }

    private void OnEnable()
    {
        if (!ActiveBoats.Contains(this))
            ActiveBoats.Add(this);
    }

    private void OnDisable()
    {
        ActiveBoats.Remove(this);
    }

    private void Awake()
    {
        physics = GetComponent<BoatPhysics>();
        if (physics == null)
            physics = gameObject.AddComponent<BoatPhysics>();
    }

    public void Configure(string id, Color color)
    {
        boatId = id;
        routeColor = color;

        Shader lineShader = Shader.Find("Universal Render Pipeline/Unlit");
        if (lineShader == null)
            lineShader = Shader.Find("Sprites/Default");
        routeRenderer = gameObject.AddComponent<LineRenderer>();
        routeRenderer.material = new Material(lineShader);
        routeRenderer.startColor = color;
        routeRenderer.endColor = color;
        routeRenderer.startWidth = 0.0025f;
        routeRenderer.endWidth = 0.0025f;
        routeRenderer.positionCount = 0;
        routeRenderer.useWorldSpace = true;
    }

    public void AcceptRoute(RoutePlan plan)
    {
        if (plan.boat_id != boatId || plan.version <= acceptedVersion)
            return;
        acceptedVersion = plan.version;
        route.Clear();
        waypointIndex = 0;

        if (plan.waypoints != null)
        {
            foreach (RouteWaypoint point in plan.waypoints)
                route.Add(new Vector3(
                    CoordinateConverter.CmToWorld(point.x, point.y, 0f).x,
                    0f,
                    CoordinateConverter.CmToWorld(point.x, point.y, 0f).z));
        }
        emergencyStopped = false;
        missionStatus = plan.algorithm ?? "外部规划任务";
        physics?.SetDocked(useKinematicAutopilot);
        DrawRoute();
    }

    /// <summary>
    /// Installs a world-space route generated by the built-in dispatcher. This
    /// keeps the simulation usable when the optional UDP planner is not running.
    /// </summary>
    public void SetLocalRoute(IEnumerable<Vector3> waypoints, string status)
    {
        route.Clear();
        waypointIndex = 0;
        if (waypoints != null)
        {
            foreach (Vector3 waypoint in waypoints)
                route.Add(new Vector3(waypoint.x, 0f, waypoint.z));
        }

        emergencyStopped = false;
        missionStatus = string.IsNullOrEmpty(status) ? "执行任务" : status;
        physics?.SetDocked(useKinematicAutopilot);
        DrawRoute();
    }

    public void SetMissionStatus(string status)
    {
        missionStatus = status;
    }

    public void DockAt(Vector3 position, Quaternion rotation)
    {
        reservedTick = -1f;
        WaitingForTraffic = false;
        route.Clear();
        waypointIndex = 0;
        emergencyStopped = false;
        missionStatus = "泊位待命";
        if (routeRenderer != null)
            routeRenderer.positionCount = 0;
        physics?.DockAt(position, rotation);
    }

    public void EmergencyStop()
    {
        emergencyStopped = true;
        if (physics != null)
            physics.Brake();
    }

    public void Resume()
    {
        emergencyStopped = false;
    }

    private void FixedUpdate()
    {
        fixedTickCount++;
        if (physics == null)
            return;

        if (emergencyStopped)
        {
            physics.SetControls(0f, 0f);
            physics.Brake();
            return;
        }

        if (useKinematicAutopilot)
        {
            RunKinematicAutopilot();
            return;
        }

        AdvanceWaypoints();

        if (waypointIndex >= route.Count)
        {
            physics.SetControls(0f, 0f);
            return;
        }

        Vector3 target = PickLookaheadTarget();
        Vector3 toTarget = target - transform.position;
        toTarget.y = 0f;
        float distance = toTarget.magnitude;
        if (distance < 0.000001f)
        {
            physics.SetControls(0f, 0f);
            return;
        }

        Vector3 desired = toTarget / distance;
        Vector3 steering = CalculateAvoidance(desired);

        float heading = Mathf.Atan2(transform.forward.x, transform.forward.z) * Mathf.Rad2Deg;
        float desiredHeading = Mathf.Atan2(steering.x, steering.z) * Mathf.Rad2Deg;
        float headingError = Mathf.DeltaAngle(heading, desiredHeading);

        // PD rudder: proportional to heading error, damped by yaw rate.
        float rudder = Mathf.Clamp(
            headingError * rudderGain - physics.YawRateDeg * rudderDampGain, -40f, 40f);

        // Speed: cruise, scaled down near the target and at large heading error
        // (the low floor breaks the circular-orbit limit cycle around waypoints).
        float desiredSpeed = Mathf.Min(cruiseSpeed, Mathf.Max(distanceSpeedFloor, distance * 1.2f));
        desiredSpeed = Mathf.Min(desiredSpeed,
            cruiseSpeed * Mathf.Max(headingErrSpeedFloor, 1f - Mathf.Abs(headingError) * headingErrSpeedGain));

        float throttle = Mathf.Clamp((desiredSpeed - physics.ForwardSpeed) * 9f, 0f, 1f);

        physics.SetControls(throttle, rudder);
    }

    private void RunKinematicAutopilot()
    {
        AdvanceWaypoints();
        if (waypointIndex >= route.Count)
            return;

        // Kinematic missions use sparse semantic waypoints (launch gate,
        // casualty, home berth). Looking through the casualty waypoint toward
        // home made the boat turn away just before entering rescue range.
        // Always acquire the current waypoint precisely; AdvanceWaypoints()
        // remains the sole authority allowed to consume it.
        Vector3 target = route[waypointIndex];
        Vector3 position = transform.position;
        Vector3 toTarget = target - position;
        toTarget.y = 0f;
        if (toTarget.sqrMagnitude < 0.000001f)
            return;

        Vector3 desiredDirection = CalculateAvoidance(toTarget.normalized);
        bool berthLane = Mathf.Abs(position.x) < 0.155f && Mathf.Abs(position.z) < 0.125f;
        if (berthLane) desiredDirection = toTarget.normalized;
        Quaternion desiredRotation = Quaternion.LookRotation(desiredDirection, Vector3.up);
        Quaternion nextRotation = Quaternion.RotateTowards(
            transform.rotation, desiredRotation, turnSpeedDegrees * Time.fixedDeltaTime);

        Vector3 nextForward = nextRotation * Vector3.forward;
        nextForward.y = 0f;
        float alignment = Mathf.Clamp01(Vector3.Dot(nextForward.normalized, desiredDirection));
        float step = cruiseSpeed * Mathf.Lerp(0.22f, 1f, alignment) * Time.fixedDeltaTime;
        Vector3 nextPosition = position;
        WaitingForTraffic = true;
        // Steering must change translation, not just the visible heading. Try
        // starboard first, then alternatives; reject swept hull intersections.
        float[] offsets = { 0f, 25f, -25f, 50f, -50f, 80f, -80f, 110f, -110f, 150f, -150f, 180f };
        foreach (float offset in offsets)
        {
            if (berthLane && offset != 0f) continue;
            Vector3 direction = Quaternion.AngleAxis(offset, Vector3.up) * desiredDirection;
            Vector3 candidate = position + direction * Mathf.Min(step, toTarget.magnitude);
            Quaternion rotation = Quaternion.RotateTowards(transform.rotation,
                Quaternion.LookRotation(direction), turnSpeedDegrees * Time.fixedDeltaTime);
            if (!SafeMovement(position, candidate, transform.rotation, rotation))
                continue;
            nextPosition = candidate;
            nextRotation = rotation;
            WaitingForTraffic = false;
            break;
        }
        if (WaitingForTraffic)
            nextRotation = transform.rotation;
        // Keep the model origin on the design waterline. The rendered waves
        // remain visual; this prevents high-frequency vertical jitter.
        nextPosition.y = WaterSystem.Instance != null ? WaterSystem.Instance.waterLevelY : 0f;
        reservedPosition = nextPosition;
        reservedRotation = nextRotation;
        reservedTick = Time.fixedTime;
        physics.MoveKinematic(nextPosition, nextRotation);
    }

    private bool SafeMovement(Vector3 start, Vector3 end, Quaternion from, Quaternion to)
    {
        // Preserve station corridors while taking local detours.
        if (Mathf.Abs(end.x) < 0.155f && Mathf.Abs(end.z) < 0.125f &&
            !(Mathf.Abs(end.x) >= 0.100f &&
              Mathf.Min(Mathf.Abs(end.z - 0.040f), Mathf.Abs(end.z + 0.040f)) <= 0.020f))
            return false;
        if (Mathf.Abs(end.x) > 0.29f || Mathf.Abs(end.z) > 0.29f)
            return false;
        foreach (BoatController other in ActiveBoats)
        {
            if (other == null || other == this) continue;
            Vector3 otherEnd = other.reservedTick == Time.fixedTime
                ? other.reservedPosition : other.transform.position;
            Quaternion otherRotation = other.reservedTick == Time.fixedTime
                ? other.reservedRotation : other.transform.rotation;
            for (int sample = 0; sample <= 4; sample++)
            {
                float t = sample / 4f;
                if (HullGap(this, Vector3.Lerp(start, end, t), Quaternion.Slerp(from, to, t),
                    other, Vector3.Lerp(other.transform.position, otherEnd, t),
                    Quaternion.Slerp(other.transform.rotation, otherRotation, t)) < 0.001f)
                    return false;
            }
        }
        return true;
    }

    public static float HullGap(BoatController a, Vector3 ap, Quaternion ar,
        BoatController b, Vector3 bp, Quaternion br)
    {
        // Capsules enclose the full rectangular hull, including its corners.
        Vector3 af = ar * Vector3.forward * a.physics.hullLength * 0.5f;
        Vector3 bf = br * Vector3.forward * b.physics.hullLength * 0.5f;
        Vector3 p = ap - af, q = bp - bf, u = af * 2f, v = bf * 2f;
        p.y = q.y = u.y = v.y = 0f;
        float aa = Vector3.Dot(u, u), bb = Vector3.Dot(u, v), cc = Vector3.Dot(v, v);
        Vector3 w = p - q;
        float dd = Vector3.Dot(u, w), ee = Vector3.Dot(v, w);
        float denominator = aa * cc - bb * bb;
        float s = denominator > 1e-10f ? Mathf.Clamp01((bb * ee - cc * dd) / denominator) : 0f;
        float t = Mathf.Clamp01((bb * s + ee) / Mathf.Max(cc, 1e-10f));
        s = Mathf.Clamp01((bb * t - dd) / Mathf.Max(aa, 1e-10f));
        return (p + s * u - q - t * v).magnitude -
            (a.physics.hullBeam + b.physics.hullBeam) * 0.5f;
    }

    /// <summary>
    /// Consumes waypoints strictly in order. A previous look-ahead skip treated
    /// a route ending at the current berth as already complete, so closed
    /// launch-and-return routes vanished on their first physics frame.
    /// </summary>
    private void AdvanceWaypoints()
    {
        Vector3 position = transform.position;
        while (waypointIndex < route.Count &&
               HorizontalDistance(route[waypointIndex], position) <= waypointTolerance)
            waypointIndex++;
    }

    /// <summary>
    /// Returns the first waypoint at least lookaheadDistance ahead of the hull
    /// along the route (distance-based, so behaviour is independent of the
    /// planner's waypoint spacing).
    /// </summary>
    private Vector3 PickLookaheadTarget()
    {
        Vector3 position = transform.position;
        Vector3 next = route[waypointIndex];
        float dNext = HorizontalDistance(next, position);
        if (dNext >= lookaheadDistance)
            return next;

        float accumulated = dNext;
        Vector3 previous = next;
        for (int i = waypointIndex + 1; i < route.Count; i++)
        {
            Vector3 point = route[i];
            accumulated += HorizontalDistance(point, previous);
            if (accumulated >= lookaheadDistance)
                return point;
            previous = point;
        }
        return route[route.Count - 1];
    }

    private static float HorizontalDistance(Vector3 a, Vector3 b)
    {
        float dx = a.x - b.x;
        float dz = a.z - b.z;
        return Mathf.Sqrt(dx * dx + dz * dz);
    }

    private void Update()
    {
        if (routeRenderer != null && route.Count > 0)
            DrawRoute();
    }

    private void DrawRoute()
    {
        if (routeRenderer == null)
            return;
        routeRenderer.positionCount = route.Count + 1;
        routeRenderer.SetPosition(0, transform.position + Vector3.up * 0.005f);
        for (int i = 0; i < route.Count; i++)
        {
            Vector3 point = route[i];
            point.y = WaterSystem.HeightAt(point.x, point.z) + 0.005f;
            routeRenderer.SetPosition(i + 1, point);
        }
    }

    private Vector3 CalculateAvoidance(Vector3 desiredDirection)
    {
        Vector3 steering = desiredDirection;
        foreach (BoatController other in ActiveBoats)
        {
            if (other == null || other == this)
                continue;
            Vector3 away = transform.position - other.transform.position;
            away.y = 0f;
            float distance = away.magnitude;
            if (distance >= avoidanceRadius)
                continue;

            if (distance < 0.0001f)
                away = transform.right;
            else
                away /= distance;

            float strength = 1f - Mathf.Clamp01(distance / avoidanceRadius);
            Vector3 towardOther = -away;
            float threat = Mathf.Max(0f, Vector3.Dot(desiredDirection, towardOther));
            steering += away * strength * (1.25f + threat);

            // Head-on approach: both vessels pass to their own starboard side.
            if (threat > 0.45f)
            {
                Vector3 starboard = Vector3.Cross(Vector3.up, desiredDirection).normalized;
                steering += starboard * strength * 1.10f;
            }
        }
        steering.y = 0f;
        return steering.sqrMagnitude > 0.000001f ? steering.normalized : desiredDirection;
    }
}
